<?php
namespace cms\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Description of Role
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="roles")
 * @package Core
 * @author adodds
 */
class Role extends Entity {
    
    /**
     *
     * @var integer $id autogenerated id
     * @ORM\Column(name="id", type="integer",nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
    
    /**
     *
     * @var string
     * @ORM\Column(type="string",length=75,nullable=false)
     */
    private $name;
    
    /**
     *
     * @var boolean
     * @ORM\Column(type="boolean",nullable=false)
     */
    private $active;
    
    /**
     *
     * @var boolean
     * @ORM\Column(type="boolean",nullable=false)
     */    
    private $public;
    
    /**
     *
     * @var boolean
     * @ORM\Column(type="boolean",nullable=false)
     */    
    private $hidden;
    
    /**
     *
     * @var datetime
     * @ORM\Column(type="datetime",nullable=false)
     */
    private $modifiedDate;
    
    /**
     *
     * @var datetime
     * @ORM\Column(type="datetime",nullable=false)
     */
    private $addDate;
    
    /**
     *
     * @var User user added this role
     * @ORM\ManyToOne(targetEntity="cms\Entity\User",cascade={"persist","remove"})
     */
    private $user;
    
    protected $listFields = array(
                                'Select'=>'id',
                                'Name'=>'name',
                            );
    
    /**
     * Set object property
     * @param string $property
     * @param mixed $value 
     */
    public function __set($property, $value) {
        $this->{$property} = $value;
    }
    
    /**
     * Return object property
     * @param string $property 
     */
    public function __get($property) {
        return $this->{$property};
    }
    
    /**
     * Function Called Before Persist
     * @ORM\PrePersist
     */
    public function prePersist() {
        if(!($this->addDate instanceof \DateTime)) {
            $this->addDate = new \DateTime();
        }
        $this->modifiedDate = new \DateTime();
    }
}