<?php
namespace cms\Entity\User;

use Doctrine\ORM\Mapping as ORM;
use cms\Entity\Entity;

/**
 * User phone numbers
 * @author adodds
 * date 23-May-2011 15:05:03
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="user_phones")
 * @package User
 * @version 1
 */
class Phone extends Entity {
    
    /**
     *
     * @var integer $id autogenerated id
     * @ORM\Column(name="id", type="integer",nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
    
    /**
     *
     * @var string Phone Number
     * @ORM\Column(type="text",nullable=false) 
     */
    private $phone;
    
    /**
     *
     * @var string Phone number type
     * @ORM\Column(type="string",length=20,nullable=false) 
     */
    private $type;
    
    /**
     *
     * @var Boolean flag to set if phone number is primary
     * @ORM\Column(type="boolean") 
     */
    private $primaryNumber;
    
    /**
     *
     * @var datetime date phone number was modified
     * @ORM\Column(type="datetime",nullable=false) 
     */
    private $modifiedDate;
    
    /**
     *
     * @var datetime date phone number was added
     * @ORM\Column(type="datetime",nullable=false) 
     */
    private $addDate;
    
    /**
     *
     * @var User user who this phone number belongs to
     * @ORM\ManyToOne(targetEntity="cms\Entity\User",inversedBy="phones")
     */
    private $user;
    
    /**
     * @ORM\PrePersist
     */
    public function prePersist() {
        if(!($this->addDate instanceof \DateTime)) {
            $this->addDate = new \DateTime();
        }
        $this->modifiedDate = new \DateTime();
    }
    
    /**
     * Set object property
     * @param string $property
     * @param mixed $value 
     */
    public function __set($property, $value) {
        $this->{$property} = $value;
    }
    
    /**
     * Return object property
     * @param string $property
     * @return mixed 
     */
    public function __get($property) {
        return $this->{$property};
    }

    public function getArrayCopy() {
        $keys = array('id','type','phone','primaryNumber');
        $return = array();
        foreach($keys as $key=>$field) {
            if(is_object($this->$field)) {
                if(($this->$field instanceof \DateTime)) {
                    $return[$field] = $this->$field->format('r');
                }
                elseif(property_exists(get_class($this->$field), 'id')) {
                    $return[$field] = $this->$field->id;
                }
                else {
                    for($i=0;$i<count($this->$field);$i++) {
                        $return[$field][$i] = $this->{$field}[$i]->getArrayCopy();
                    }
                }
            }
            else {
                $return[$field] = $this->{$field};
            }
        }
        return $return;
    }
}