<?php
namespace cms\Entity\Meta;

use Doctrine\ORM\Mapping as ORM;
use cms\Entity\Entity;
/**
 * Meta Setup
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="meta_keys")
 * @package Page
 * @author adodds
 */
class Key extends Entity {
    
    /**
     *
     * @var integer $id autogenerated id
     * @ORM\Column(name="id", type="integer",nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;
    
    /**
     * @var string
     * @ORM\Column(type="string",length=150,nullable=false)
     */
    protected $name;
    
    /**
     * @var string
     * @ORM\Column(type="string",length=150,nullable=false)
     */
    protected $value;
    
    /**
     *
     * @var object user
     * @ORM\ManyToOne(targetEntity="\cms\Entity\User",cascade={"persist","remove"})
     */
    protected $user;
    
    /**
     * 
     * @var datetime
     * @ORM\Column(type="datetime",nullable=false)
     */
    protected $addTime;
    
    /**
     *
     * @var boolean
     * @ORM\Column(type="boolean",nullable=false)
     */
    protected $active;
    
    /**
     * 
     * @var datetime
     * @ORM\Column(type="datetime",nullable=false)
     */
    protected $modified;
    
    /**
     * @ORM\ManyToOne(targetEntity="\cms\Entity\Meta",inversedBy="keys",cascade={"persist","remove"})
     */
    protected $meta;
    
    public function __get($what = '') {
        return $this->{$what};
    }
    
    public function __set($what, $value) {
        $this->{$what} = $value;
    }
    
    /**
     * @ORM\PrePersist
     */
    public function prePersist() {
        if(!($this->addTime instanceof \DateTime)) {
            $this->addTime = new \DateTime();
        }
        $this->modified = new \DateTime();
    }
}